databases:
  - name: jobappdb  # render launches an instance of postgresql and with it creates a database jobappdb: this name is for infrastructure management
    plan: free # Render’s free PostgreSQL tier
    databaseName: jobappdb # actual name for the DATABASE: CREATE DATABASE jobappdb
    user: myuser  # user created with access to this DB: jobappdb

services:
  - type: web # deploys a public web services: handles http request
    plan: free # Render’s free instance
    name: jobapp # Service name shown in dashboard; part of the default URL
    runtime: python # Uses Python runtime;
    buildCommand: './backend/build.sh' #  # Runs during deployment. Typically installs deps and runs migrations:
    startCommand: 'python -m gunicorn thebackend.wsgi:application'  # Starts Gunicorn WSGI server to serve Django app.
    envVars:
      - key: DATABASE_URL # Django uses this to connect to PostgreSQL.
        fromDatabase: # fromDatabase dynamically injects the full connection string (host, port, user, password, SSL mode).
          name: jobappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value : true
