# Generated by Django 6.0.3 on 2026-03-21 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('hybrid', 'Hybrid')], max_length=255)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('internship', 'Internship'), ('senior', 'Senior'), ('attachment', 'Attachment')], max_length=255)),
                ('job_description', models.CharField(max_length=1000)),
                ('job_requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=15)),
                ('location', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('company_name', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('mission', models.CharField(max_length=1500)),
                ('logo', models.CharField(max_length=500)),
            ],
        ),
    ]
