# Generated by Django 6.0.3 on 2026-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.CharField(max_length=2500),
        ),
    ]
