# Generated by Django 6.0.3 on 2026-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('internship', 'Internship'), ('senior', 'Senior'), ('attachment', 'Attachment'), ('mid-senior', 'Mid-Senior')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=255),
        ),
    ]
