# Generated by Django 6.0.3 on 2026-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_experience_level_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('contract', 'Contract')], max_length=255),
        ),
    ]
